spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true

server:
  port: 8090
  
  
sql-data-statements:
  sqlDataConfigList:
  -
    sqlName: UNIT_TEST_SQL
    queryString: "select * from microservice_mappings where type in :type and servicename= :servicename"
    tableName: none
  -
    sqlName: UNIT_TEST_SQL1
    queryString: none
    tableName: microservice_mappings
  -
    sqlName: UNIT_TEST_SQL2
    queryString: none
    tableName: microservice_mappings