INSERT INTO MICROSERVICE_MAPPINGS(SERVICENAME, URL, TYPE) VALUES('LoanHistory','/v1/crud/test','POST');
INSERT INTO MICROSERVICE_MAPPINGS(SERVICENAME, URL, TYPE) VALUES('FlexPlan','/v1/crud/test','PUT');
INSERT INTO MICROSERVICE_MAPPINGS(SERVICENAME, URL, TYPE) VALUES('BalconOffers','/v1/crud/test','POST');